# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tftp.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'tftp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntftp.proto\x12\x05tftp2\"7\n\x08Transfer\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12\x19\n\x04mode\x18\x02 \x02(\x0e\x32\x0b.tftp2.Mode\"&\n\x04\x44\x61ta\x12\x10\n\x08\x62locknum\x18\x01 \x02(\r\x12\x0c\n\x04\x62ody\x18\x02 \x02(\x0c\"\x17\n\x03\x41\x63k\x12\x10\n\x08\x62locknum\x18\x01 \x02(\r\"6\n\x05\x45rror\x12\x1e\n\x04\x63ode\x18\x01 \x02(\x0e\x32\x10.tftp2.ErrorCode\x12\r\n\x05\x64\x65scr\x18\x02 \x02(\t\"%\n\x07\x41rchive\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04size\x18\x02 \x02(\r\"D\n\x08ListItem\x12!\n\x07\x61rchive\x18\x01 \x01(\x0b\x32\x0e.tftp2.ArchiveH\x00\x12\r\n\x03\x64ir\x18\x02 \x01(\tH\x00\x42\x06\n\x04item\".\n\x0cListResponse\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.tftp2.ListItem\"!\n\x04Move\x12\x0b\n\x03src\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x01(\t\"\x90\x02\n\x08Mensagem\x12\x1e\n\x03rrq\x18\x01 \x01(\x0b\x32\x0f.tftp2.TransferH\x00\x12\x1e\n\x03wrq\x18\x02 \x01(\x0b\x32\x0f.tftp2.TransferH\x00\x12\x1b\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x0b.tftp2.DataH\x00\x12\x19\n\x03\x61\x63k\x18\x04 \x01(\x0b\x32\n.tftp2.AckH\x00\x12\x1d\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x0c.tftp2.ErrorH\x00\x12\x0e\n\x04list\x18\x06 \x01(\tH\x00\x12(\n\tlist_resp\x18\x07 \x01(\x0b\x32\x13.tftp2.ListResponseH\x00\x12\x0f\n\x05mkdir\x18\x08 \x01(\tH\x00\x12\x1b\n\x04move\x18\t \x01(\x0b\x32\x0b.tftp2.MoveH\x00\x42\x05\n\x03msg*)\n\x04Mode\x12\t\n\x05octet\x10\x01\x12\x0c\n\x08netascii\x10\x02\x12\x08\n\x04mail\x10\x03*\x9c\x01\n\tErrorCode\x12\r\n\tundefined\x10\x01\x12\x10\n\x0c\x66ileNotFound\x10\x02\x12\x13\n\x0f\x61\x63\x63\x65ssViolation\x10\x03\x12\x12\n\x0enotEnoughSpace\x10\x04\x12\x14\n\x10illegalOperation\x10\x05\x12\x0e\n\nunknownTID\x10\x06\x12\x0e\n\nfileExists\x10\x07\x12\x0f\n\x0bunknownUser\x10\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tftp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODE']._serialized_start=666
  _globals['_MODE']._serialized_end=707
  _globals['_ERRORCODE']._serialized_start=710
  _globals['_ERRORCODE']._serialized_end=866
  _globals['_TRANSFER']._serialized_start=21
  _globals['_TRANSFER']._serialized_end=76
  _globals['_DATA']._serialized_start=78
  _globals['_DATA']._serialized_end=116
  _globals['_ACK']._serialized_start=118
  _globals['_ACK']._serialized_end=141
  _globals['_ERROR']._serialized_start=143
  _globals['_ERROR']._serialized_end=197
  _globals['_ARCHIVE']._serialized_start=199
  _globals['_ARCHIVE']._serialized_end=236
  _globals['_LISTITEM']._serialized_start=238
  _globals['_LISTITEM']._serialized_end=306
  _globals['_LISTRESPONSE']._serialized_start=308
  _globals['_LISTRESPONSE']._serialized_end=354
  _globals['_MOVE']._serialized_start=356
  _globals['_MOVE']._serialized_end=389
  _globals['_MENSAGEM']._serialized_start=392
  _globals['_MENSAGEM']._serialized_end=664
# @@protoc_insertion_point(module_scope)
